import sys
import os
import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import yfinance as yf
import torch

# Ensure the local directory is in system path to import Kronos model modules
sys.path.append(os.path.abspath(os.path.dirname(__file__)))

try:
    from model import Kronos, KronosTokenizer, KronosPredictor
except ImportError as e:
    st.error(
        f"❌ Could not import Kronos module: {e}. "
        "Please make sure the 'model' directory from the Kronos repository is present in your repository root."
    )
    st.stop()

# -------------------------------------------------------------------
# Page Configuration
# -------------------------------------------------------------------
st.set_page_config(
    page_title="Kronos Financial AI Forecaster",
    page_icon="📈",
    layout="wide"
)

st.title("📈 Kronos Financial AI Market Forecaster")
st.caption("Open-source Foundation Model for K-Line Candlestick Time-Series Forecasting")

# -------------------------------------------------------------------
# Model Loader (Cached to avoid re-loading on every interaction)
# -------------------------------------------------------------------
MODEL_MAP = {
    "Kronos-mini (4.1M params | 2048 max context)": {
        "model_id": "NeoQuasar/Kronos-mini",
        "tokenizer_id": "NeoQuasar/Kronos-Tokenizer-2k",
        "max_context": 2048,
    },
    "Kronos-small (24.7M params | 512 max context)": {
        "model_id": "NeoQuasar/Kronos-small",
        "tokenizer_id": "NeoQuasar/Kronos-Tokenizer-base",
        "max_context": 512,
    },
    "Kronos-base (102.3M params | 512 max context)": {
        "model_id": "NeoQuasar/Kronos-base",
        "tokenizer_id": "NeoQuasar/Kronos-Tokenizer-base",
        "max_context": 512,
    },
}

@st.cache_resource(show_spinner="Loading Kronos AI model weights...")
def load_predictor(model_choice_key, device_type):
    cfg = MODEL_MAP[model_choice_key]
    tokenizer = KronosTokenizer.from_pretrained(cfg["tokenizer_id"])
    model = Kronos.from_pretrained(cfg["model_id"])
    model.to(device_type)
    predictor = KronosPredictor(model, tokenizer, max_context=cfg["max_context"])
    return predictor, cfg["max_context"]

# -------------------------------------------------------------------
# Sidebar Controls
# -------------------------------------------------------------------
st.sidebar.header("⚙️ Model Architecture")
model_choice = st.sidebar.selectbox(
    "Select Model Size",
    list(MODEL_MAP.keys()),
    index=1
)

# Auto-detect hardware
device = "cuda" if torch.cuda.is_available() else "cpu"
st.sidebar.info(f"Hardware Acceleration: **{device.upper()}**")

st.sidebar.header("📊 Data Input")
data_source = st.sidebar.radio("Data Provider", ["Yahoo Finance", "CSV Upload"])

if data_source == "Yahoo Finance":
    ticker = st.sidebar.text_input("Ticker Symbol", value="AAPL")
    interval = st.sidebar.selectbox("Interval", ["1d", "1h", "15m", "5m"], index=0)
    period = st.sidebar.selectbox("Period", ["60d", "100d", "1y", "2y"], index=2)
else:
    uploaded_file = st.sidebar.file_uploader(
        "Upload CSV (Columns required: timestamps, open, high, low, close)", type=["csv"]
    )

st.sidebar.header("🔮 Prediction Parameters")
pred_len = st.sidebar.slider("Forecast Horizon (Steps Ahead)", min_value=5, max_value=120, value=30, step=5)
lookback_window = st.sidebar.slider("Historical Lookback Window", min_value=50, max_value=512, value=300, step=10)

st.sidebar.header("🎲 Monte Carlo Sampling")
temperature = st.sidebar.slider("Temperature (T)", min_value=0.1, max_value=2.0, value=1.0, step=0.1)
top_p = st.sidebar.slider("Nucleus Sampling (top_p)", min_value=0.1, max_value=1.0, value=0.9, step=0.05)
sample_count = st.sidebar.slider("Monte Carlo Path Count", min_value=1, max_value=25, value=10, step=1)

# -------------------------------------------------------------------
# Data Fetching & Preprocessing
# -------------------------------------------------------------------
@st.cache_data(ttl=300)
def fetch_financial_data(symbol, interval, period):
    try:
        data = yf.download(symbol, period=period, interval=interval, progress=False)
        if data.empty:
            return None
        
        # Flatten MultiIndex columns if generated by yfinance
        if isinstance(data.columns, pd.MultiIndex):
            data.columns = data.columns.get_level_values(0)
        
        data = data.reset_index()
        date_col = 'Date' if 'Date' in data.columns else 'Datetime'
        
        data = data.rename(columns={
            date_col: 'timestamps',
            'Open': 'open',
            'High': 'high',
            'Low': 'low',
            'Close': 'close',
            'Volume': 'volume'
        })
        
        # Fill missing volume/amount if absent
        if 'volume' not in data.columns:
            data['volume'] = 0.0
        data['amount'] = data['close'] * data['volume']
        
        return data[['timestamps', 'open', 'high', 'low', 'close', 'volume', 'amount']]
    except Exception as e:
        st.error(f"Error fetching data: {e}")
        return None

# Load dataset
df = None
if data_source == "Yahoo Finance":
    with st.spinner(f"Downloading market data for {ticker}..."):
        df = fetch_financial_data(ticker, interval, period)
elif uploaded_file is not None:
    try:
        df = pd.read_csv(uploaded_file)
        df['timestamps'] = pd.to_datetime(df['timestamps'])
        if 'volume' not in df.columns:
            df['volume'] = 0.0
        if 'amount' not in df.columns:
            df['amount'] = df['close'] * df['volume']
    except Exception as e:
        st.error(f"Invalid CSV structure: {e}")

# -------------------------------------------------------------------
# Main Forecast Execution
# -------------------------------------------------------------------
if df is not None and not df.empty:
    actual_lookback = min(lookback_window, len(df))
    historical_df = df.tail(actual_lookback).reset_index(drop=True)

    st.subheader(f"Historical Context Window ({actual_lookback} periods)")
    
    with st.expander("🔍 View Data Table"):
        st.dataframe(historical_df.tail(10))

    if st.button("🚀 Run Kronos Forecast", type="primary"):
        predictor, max_ctx = load_predictor(model_choice, device)

        # Enforce model context boundaries
        if len(historical_df) > max_ctx:
            historical_df = historical_df.tail(max_ctx).reset_index(drop=True)

        # Generate future timestamps sequence
        last_time = historical_df['timestamps'].iloc[-1]
        freq = pd.infer_freq(historical_df['timestamps'])
        if freq is None:
            time_diff = historical_df['timestamps'].diff().median()
            future_timestamps = [last_time + (i + 1) * time_diff for i in range(pred_len)]
        else:
            future_timestamps = pd.date_range(start=last_time, periods=pred_len + 1, freq=freq)[1:]

        x_df = historical_df[['open', 'high', 'low', 'close', 'volume', 'amount']]
        x_timestamp = historical_df['timestamps']
        y_timestamp = pd.Series(future_timestamps)

        # Run probabilistic forecast paths
        sample_predictions = []
        progress_bar = st.progress(0)

        with st.spinner("Generating Monte Carlo forecasting trajectories..."):
            for i in range(sample_count):
                pred_sample = predictor.predict(
                    df=x_df,
                    x_timestamp=x_timestamp,
                    y_timestamp=y_timestamp,
                    pred_len=pred_len,
                    T=temperature,
                    top_p=top_p,
                    sample_count=1
                )
                sample_predictions.append(pred_sample)
                progress_bar.progress((i + 1) / sample_count)
            
        progress_bar.empty()

        # Compute aggregate metrics
        close_paths = np.column_stack([p['close'].values for p in sample_predictions])
        mean_forecast = close_paths.mean(axis=1)
        upper_bound = np.percentile(close_paths, 95, axis=1)
        lower_bound = np.percentile(close_paths, 5, axis=1)

        forecast_df = pd.DataFrame({
            'timestamps': y_timestamp,
            'mean_close': mean_forecast,
            'upper_95': upper_bound,
            'lower_5': lower_bound
        })

        # Display key metrics
        last_close = historical_df['close'].iloc[-1]
        final_predicted = mean_forecast[-1]
        pct_change = ((final_predicted - last_close) / last_close) * 100

        m1, m2, m3, m4 = st.columns(4)
        m1.metric("Last Close Price", f"${last_close:,.2f}")
        m2.metric("Predicted Target Price", f"${final_predicted:,.2f}", f"{pct_change:+.2f}%")
        m3.metric("5th Percentile (Bear Case)", f"${lower_bound[-1]:,.2f}")
        m4.metric("95th Percentile (Bull Case)", f"${upper_bound[-1]:,.2f}")

        # Visualization
        fig = go.Figure()

        # Historical Candlesticks
        fig.add_trace(go.Candlestick(
            x=historical_df['timestamps'],
            open=historical_df['open'],
            high=historical_df['high'],
            low=historical_df['low'],
            close=historical_df['close'],
            name="Historical Data"
        ))

        # Monte Carlo individual trajectories
        for idx in range(close_paths.shape[1]):
            fig.add_trace(go.Scatter(
                x=y_timestamp,
                y=close_paths[:, idx],
                mode='lines',
                line=dict(width=1, color='rgba(255, 165, 0, 0.2)'),
                showlegend=False,
                hoverinfo='skip'
            ))

        # 90% Confidence Interval Band
        fig.add_trace(go.Scatter(
            x=list(y_timestamp) + list(y_timestamp)[::-1],
            y=list(upper_bound) + list(lower_bound)[::-1],
            fill='toself',
            fillcolor='rgba(255, 165, 0, 0.15)',
            line=dict(color='rgba(255,255,255,0)'),
            name="90% Confidence Band",
            hoverinfo='skip'
        ))

        # Mean Forecast Line
        fig.add_trace(go.Scatter(
            x=y_timestamp,
            y=mean_forecast,
            mode='lines+markers',
            line=dict(color='orange', width=3),
            name="Kronos Mean Prediction"
        ))

        fig.update_layout(
            title="Kronos AI Forecast & Trajectories",
            xaxis_title="Time",
            yaxis_title="Price",
            template="plotly_dark",
            height=600,
            xaxis_rangeslider_visible=False
        )

        st.plotly_chart(fig, use_container_width=True)

        # Download Table
        st.subheader("📥 Export Predictions")
        st.dataframe(forecast_df)
        csv_data = forecast_df.to_csv(index=False).encode('utf-8')
        st.download_button(
            label="Download Forecast CSV",
            data=csv_data,
            file_name=f"kronos_forecast_{ticker if data_source == 'Yahoo Finance' else 'uploaded'}.csv",
            mime="text/csv"
        )
else:
    st.info("👈 Enter a ticker symbol or upload data in the sidebar to begin.")
